### PR TITLE
Adds more font files

### PR DESCRIPTION
**Pull request by FredDsR**
Adds more font files to solve this issue: #1 

The fonts added:
- Anson
- Helvetica
- Arial
- Brilliant
- Knile

### CODE REVIEW

**Comment by ieshaan12** [comment]
@FredDsR I'd like to know that if these fonts are open-sourced or not

**Comment by FredDsR** [comment]
> @FredDsR I'd like to know that if these fonts are open-sourced or not

I didn't take that into account. Apparently some of these fonts are not open. I'll fix it!

**Comment by FredDsR** [comment]
I deleted the other sources and added new ones meeting the open source requirement.

- Urbanist: https://github.com/coreywho/Urbanist
- FiraSans: https://fonts.google.com/specimen/Fira+Sans?sidebar.open=true&selection.family=Fira+Sans
- PublicSans: https://github.com/uswds/public-sans
- Inter: https://fonts.google.com/specimen/Inter?sidebar.open=true&selection.family=Inter
- Manrope: https://manropefont.com/

**Comment by FredDsR** [comment]
Hello, don't forget me! :laughing:

**Comment by ieshaan12** [comment]
Oh my god, I'm so sorry, merging it now.

**Pull request merged**
